
version: '3.9'

services:
  app:
    image: 'credit:latest'
    build:
      context: .
    ports:
    - 8074:8080
    container_name: creditapplication
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/creditdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect


  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditdb
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 2211:8080