version: '3.9'
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: library/postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: kozakiewicz41
      POSTGRES_DB: Credit
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 2211:8080